set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property PACKAGE_PIN R2 [get_ports start]					
	set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property PACKAGE_PIN V17 [get_ports {sw_pins[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pins[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_pins[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pins[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_pins[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pins[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_pins[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pins[3]}]

set_property PACKAGE_PIN W7 [get_ports {seg_pins[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_pins[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_pins[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_pins[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_pins[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_pins[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_pins[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[6]}]
set_property PACKAGE_PIN V7 [get_ports {seg_pins[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_pins[7]}]

set_property PACKAGE_PIN U2 [get_ports {an_pins[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an_pins[0]}]
set_property PACKAGE_PIN U4 [get_ports {an_pins[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an_pins[1]}]
set_property PACKAGE_PIN V4 [get_ports {an_pins[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an_pins[2]}]
set_property PACKAGE_PIN W4 [get_ports {an_pins[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an_pins[3]}]

set_property PACKAGE_PIN T18 [get_ports {btn_pins[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {btn_pins[0]}]
set_property PACKAGE_PIN T17 [get_ports {btn_pins[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {btn_pins[1]}]
set_property PACKAGE_PIN W19 [get_ports {btn_pins[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {btn_pins[2]}]
set_property PACKAGE_PIN U17 [get_ports {btn_pins[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {btn_pins[3]}]
set_property PACKAGE_PIN U18 [get_ports {btn_pins[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {btn_pins[4]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]